# Generated by Django 3.1.7 on 2021-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_noteboocks_smartphones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphones',
            old_name='accum_volue',
            new_name='accum_value',
        ),
        migrations.AlterField(
            model_name='noteboocks',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
