# Generated by Django 3.1.7 on 2021-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_auto_20210317_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие SD карты'),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='sd_values_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем sd карты'),
        ),
    ]
