# Generated by Django 3.1.7 on 2021-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_auto_20210317_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='sd_values_max',
            field=models.CharField(blank=True, choices=[('low-_sd', '1 GB'), ('low_sd', '2 GB'), ('low+_sd', '4 GB'), ('mid-_sd', '8 GB'), ('mid_sd', '16 GB'), ('mid+_sd', '32 GB'), ('hight-_sd', '64 GB'), ('hight_sd', '128 GB'), ('hight+_sd', '256 GB'), ('very_hight_sd', '512 GB')], max_length=255, null=True, verbose_name='Максимальный объем sd карты'),
        ),
    ]
