# Generated by Django 3.1.7 on 2021-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_auto_20210318_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='sd_values_max',
            field=models.CharField(blank=True, choices=[('1 GB', 'low-_sd'), ('2 GB', 'low_sd'), ('4 GB', 'low+_sd'), ('8 GB', 'mid-_sd'), ('16 GB', 'mid_sd'), ('32 GB', 'mid+_sd'), ('64 GB', 'hight-_sd'), ('128 GB', 'hight_sd'), ('256 GB', 'hight+_sd'), ('512 GB', 'very_hight_sd')], max_length=255, null=True, verbose_name='Максимальный объем sd карты'),
        ),
    ]
