# Generated by Django 3.1.7 on 2021-03-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_auto_20210318_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='sd_values_max',
            field=models.CharField(blank=True, choices=[('1 GB', '1 gb'), ('2 GB', '2 gb'), ('4 GB', '4 gb'), ('8 GB', '8 gb'), ('16 GB', '16 gb'), ('32 GB', '32 gb'), ('64 GB', '64 gb'), ('128 GB', '128 gb'), ('256 GB', '256 gb'), ('512 GB', '512 gb')], max_length=255, null=True, verbose_name='Максимальный объем sd карты'),
        ),
    ]
