# Generated by Django 3.1.7 on 2021-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_auto_20210318_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='ram',
            field=models.CharField(choices=[('1 GB', '1 gb'), ('2 GB', '2 gb'), ('4 GB', '4 gb'), ('6 GB', '6 gb'), ('8 GB', '8 gb'), ('12 GB', '12 gb'), ('16 GB', '16 gb')], max_length=255, verbose_name='Оперативная память'),
        ),
    ]
