# Generated by Django 3.1.7 on 2021-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_auto_20210318_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='resolution',
            field=models.CharField(blank=True, choices=[('1280 х 720', '720p'), ('1920 x 1080', '1080p'), ('2560 x 1440', '2K'), ('3840 x 2160', '4К')], max_length=255, null=True, verbose_name='Разрешение экрана'),
        ),
    ]
