# Generated by Django 3.1.7 on 2021-03-18 18:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_auto_20210318_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteboocks',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique_with=['category__name', 'title__name']),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique_with=['category__name', 'title__name']),
        ),
    ]
